spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: hanium
    url: jdbc:mysql://localhost:3306/pilot?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
logging.level:
  org.hibernate.SQL: debug

